In [ ]:
from funcoes import *
from fluxo import *
import pandas as pd     
import time

In [33]:

df_matriz = pd.read_excel(r"C:\Users\manoel.campos\OneDrive - SFIEMT\Área de Trabalho\AutomatizacaoERP\Base_RAs\teste.xlsx")
display(df_matriz)

,CodFilialSGE,NomeCentroCusto,NomeModalidade,CodTurma,CodMatriculaSi,CodAlunoSi,RegistroAluno,NomeAluno,TemParceria,OrigemParceria,NomeInstituicaoOrigem,Convenio
0,7,SENAI CACERES,TÉCNICO DE NÍVEL MÉDIO,TEC.199.011,64528863733,SGEMT00645288,645288,IZABELA DE FREITAS RICO,1,2,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...
1,7,SENAI CACERES,TÉCNICO DE NÍVEL MÉDIO,TEC.199.014,64172563737,SGEMT00641725,641725,LUIZ OTÁVIO NOBREGA HODNIUK,1,2,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...
2,4,SENAI RONDONOPOLIS,TÉCNICO DE NÍVEL MÉDIO,TEC.199.006,64496163668,SGEMT00644961,644961,HENRIQUE BINDELLA DE OLIVEIRA,1,0,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...
3,4,SENAI RONDONOPOLIS,TÉCNICO DE NÍVEL MÉDIO,TEC.199.006,64496663668,SGEMT00644966,644966,ANA BEATRIZ SANTANA DE SOUZA,1,0,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...
4,14,SENAI BARRA DO BUGRES,TÉCNICO DE NÍVEL MÉDIO,TEC.199.096,64747164334,SGEMT00647471,647471,EMANUELE JUSTINO DA SILVA,1,2,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...
5,14,SENAI BARRA DO BUGRES,TÉCNICO DE NÍVEL MÉDIO,TEC.199.096,64744264334,SGEMT00647442,647442,ELOAH SILVA SANTOS,1,2,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...

In [34]:
print(df_matriz.columns)

Index(['CodFilialSGE', 'NomeCentroCusto', 'NomeModalidade', 'CodTurma',
       'CodMatriculaSi', 'CodAlunoSi', 'RegistroAluno', 'NomeAluno',
       'TemParceria', 'OrigemParceria', 'NomeInstituicaoOrigem', 'Convenio'],
      dtype='str')

In [35]:
df_matriz.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CodFilialSGE           6 non-null      int64
 1   NomeCentroCusto        6 non-null      str
 2   NomeModalidade         6 non-null      str
 3   CodTurma               6 non-null      str
 4   CodMatriculaSi         6 non-null      int64
 5   CodAlunoSi             6 non-null      str
 6   RegistroAluno          6 non-null      int64
 7   NomeAluno              6 non-null      str
 8   TemParceria            6 non-null      int64
 9   OrigemParceria         6 non-null      int64
 10  NomeInstituicaoOrigem  0 non-null      float64
 11  Convenio               6 non-null      str
dtypes: float64(1), int64(5), str(6)
memory usage: 1.6 KB

In [ ]:
#python
cod_filial = []

for x in df_matriz["CodFilialSGE"]:
    cod_filial.append(x)
    
cod_filal_unique = list(dict.fromkeys(cod_filial))    
print(cod_filal_unique)

[7, 4, 14]

In [42]:
#pandas
cod_filial_unique = df_matriz["CodFilialSGE"].drop_duplicates().tolist()
display(cod_filial_unique)

[7, 4, 14]

In [ ]:
for filial in cod_filial_unique:

    df_filtrada = df_matriz[
        df_matriz["CodFilialSGE"] == filial
    ]
    

    display(df_filtrada)

,CodFilialSGE,NomeCentroCusto,NomeModalidade,CodTurma,CodMatriculaSi,CodAlunoSi,RegistroAluno,NomeAluno,TemParceria,OrigemParceria,NomeInstituicaoOrigem,Convenio
0,7,SENAI CACERES,TÉCNICO DE NÍVEL MÉDIO,TEC.199.011,64528863733,SGEMT00645288,645288,IZABELA DE FREITAS RICO,1,2,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...
1,7,SENAI CACERES,TÉCNICO DE NÍVEL MÉDIO,TEC.199.014,64172563737,SGEMT00641725,641725,LUIZ OTÁVIO NOBREGA HODNIUK,1,2,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...

,CodFilialSGE,NomeCentroCusto,NomeModalidade,CodTurma,CodMatriculaSi,CodAlunoSi,RegistroAluno,NomeAluno,TemParceria,OrigemParceria,NomeInstituicaoOrigem,Convenio
2,4,SENAI RONDONOPOLIS,TÉCNICO DE NÍVEL MÉDIO,TEC.199.006,64496163668,SGEMT00644961,644961,HENRIQUE BINDELLA DE OLIVEIRA,1,0,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...
3,4,SENAI RONDONOPOLIS,TÉCNICO DE NÍVEL MÉDIO,TEC.199.006,64496663668,SGEMT00644966,644966,ANA BEATRIZ SANTANA DE SOUZA,1,0,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...

,CodFilialSGE,NomeCentroCusto,NomeModalidade,CodTurma,CodMatriculaSi,CodAlunoSi,RegistroAluno,NomeAluno,TemParceria,OrigemParceria,NomeInstituicaoOrigem,Convenio
4,14,SENAI BARRA DO BUGRES,TÉCNICO DE NÍVEL MÉDIO,TEC.199.096,64747164334,SGEMT00647471,647471,EMANUELE JUSTINO DA SILVA,1,2,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...
5,14,SENAI BARRA DO BUGRES,TÉCNICO DE NÍVEL MÉDIO,TEC.199.096,64744264334,SGEMT00647442,647442,ELOAH SILVA SANTOS,1,2,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...

In [45]:
for filial in cod_filial_unique:

    df_filtrada = df_matriz[
        df_matriz["CodFilialSGE"] == filial
    ]

    display(df_filtrada)

,CodFilialSGE,NomeCentroCusto,NomeModalidade,CodTurma,CodMatriculaSi,CodAlunoSi,RegistroAluno,NomeAluno,TemParceria,OrigemParceria,NomeInstituicaoOrigem,Convenio
0,7,SENAI CACERES,TÉCNICO DE NÍVEL MÉDIO,TEC.199.011,64528863733,SGEMT00645288,645288,IZABELA DE FREITAS RICO,1,2,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...
1,7,SENAI CACERES,TÉCNICO DE NÍVEL MÉDIO,TEC.199.014,64172563737,SGEMT00641725,641725,LUIZ OTÁVIO NOBREGA HODNIUK,1,2,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...

,CodFilialSGE,NomeCentroCusto,NomeModalidade,CodTurma,CodMatriculaSi,CodAlunoSi,RegistroAluno,NomeAluno,TemParceria,OrigemParceria,NomeInstituicaoOrigem,Convenio
2,4,SENAI RONDONOPOLIS,TÉCNICO DE NÍVEL MÉDIO,TEC.199.006,64496163668,SGEMT00644961,644961,HENRIQUE BINDELLA DE OLIVEIRA,1,0,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...
3,4,SENAI RONDONOPOLIS,TÉCNICO DE NÍVEL MÉDIO,TEC.199.006,64496663668,SGEMT00644966,644966,ANA BEATRIZ SANTANA DE SOUZA,1,0,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...

,CodFilialSGE,NomeCentroCusto,NomeModalidade,CodTurma,CodMatriculaSi,CodAlunoSi,RegistroAluno,NomeAluno,TemParceria,OrigemParceria,NomeInstituicaoOrigem,Convenio
4,14,SENAI BARRA DO BUGRES,TÉCNICO DE NÍVEL MÉDIO,TEC.199.096,64747164334,SGEMT00647471,647471,EMANUELE JUSTINO DA SILVA,1,2,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...
5,14,SENAI BARRA DO BUGRES,TÉCNICO DE NÍVEL MÉDIO,TEC.199.096,64744264334,SGEMT00647442,647442,ELOAH SILVA SANTOS,1,2,NaN,NOVÍSSIMO ENSINO MÉDIO - C1 -1000h CRT010/2...